config/routes.rb
EclipsePhasePlayerAssistant::Application.routes.draw do
  devise_for :users

  root :to=> 'static_pages#index'

  resources :items, {except: [:show, :create, :new]}
  get '/items/new/character/:char_id' => 'items#new', :as => 'new_character_item'
  post '/items/new/character/:char_id' => 'items#create', :as => 'create_character_item'
  post '/items/destroy/:item_id/character/:char_id' => 'items#destroy', :as => 'destroy_character_item'

  resources :characters
  get '/characters/:id/inventory' => 'characters#inventory', :as => 'character_inventory'
  get '/characters/:id/notes' => 'characters#notes', :as => 'character_notes'
  put '/characters/:id/money/' => 'characters#adjust_money', :as => 'character_money'
  post '/character/:id/clear_inv' => 'items#clear_all', :as => 'clear_inventory'

  match '*path' => redirect('/')
end

app/models/character.rb
class Character < ActiveRecord::Base
  attr_accessible :name, :money, :items, :notes, :campaign

  belongs_to :user
  has_and_belongs_to_many :items

  def items_by_group
    items.all.group_by(&:category_name).sort
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :description, :item_type, :name

  belongs_to :item_type
  has_and_belongs_to_many :characters

  validates :name, :presence => true

  def type_name
    item_type.name
  end

  def category_name
    item_type.category_name
  end
end

app/models/item_category.rb
class ItemCategory < ActiveRecord::Base
  attr_accessible :name

  has_many :item_types
end

app/models/item_type.rb
class ItemType < ActiveRecord::Base
  attr_accessible :name, :item_category

  belongs_to :item_category
  has_many :items

  def category_name
    item_category.name
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :characters, :display_name

  # Associations
  has_many :characters
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_filter :authenticate_user!

  def index

  end

  def show
    @pc = Character.find(params[:id])

    # set a default tool
    if not defined? @tool then
      @tool = :inventory
    end

    redirect_to characters_url, error: 'You can only view characters you own' unless current_user.characters.include?(@pc)
  end

  def new
    @character = Character.new
  end

  def create
    @character = current_user.characters.build(params[:character])
    if @character.save then
      redirect_to character_inventory_url(@character)
    else
      flash[:error] = 'Character creation failed.'
      render :new
    end
  end

  def update
    @pc = current_user.characters.find(params[:id])
    redirect_to characters_url, error: "You can't adjust any settings for #{@pc.name}." if @pc.nil?

    if defined? params[:character][:money] then
      @pc.money += params[:character][:money].to_f
    end

    if update_has_notes then
      @pc.notes = params[:character][:notes]
    end

    @pc.save
    redirect_to :back
  end

  def update_has_notes
    defined? params[:character][:notes] and
        !(params[:character][:notes].nil?)
  end

  # This is really a 'sub-view' of Show.  Calling it in its own action to segregate some variables that only pertain
  # to this type of view
  def inventory
    # Call the main 'show' implementation to get our base data loaded
    show

    # indicate that we're using the inventory view
    @tool = :inventory

    # display the show view
    render :show
  end

  def notes
    show

    @tool = :notes

    render :show
  end

  def adjust_money
    @pc = current_user.characters.find(params[:id])
    redirect_to characters_url, error: "You can't adjust money for #{@pc.name}." if @pc.nil?


  end

  def destroy
    @pc = current_user.characters.find(params[:id])
    if @pc then
      @pc.destroy
      redirect_to characters_url
    else
      redirect_to characters_url, error: "Unknown character"
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authenticate_user!

  def new
    @item = Item.new
  end

  def create
    begin
      @pc = current_user.characters.find(params[:char_id])
      redirect_to(characters_url, :error => 'You cannot add items to characters you do not own.') if @pc.nil?

      data = params[:item]
      @item = Item.new()
      @item.name = data[:name]
      @item.description = data[:description]
      @item.item_type = ItemType.find(data[:item_type])

      if @item.save then
        @pc.items << @item
        redirect_to character_inventory_url(@pc)
      else
        render :new if not @item.save
      end
    rescue => exception
      flash[:error] = "Unable to create this item due to an exception: '#{exception.message}'"
      @item = Item.new
      render :new
    end
  end

  def destroy
    begin
      @pc = current_user.characters.find(params[:char_id])
      redirect_to(characters_url, :error => 'You cannot remove items from characters you do not own.') if @pc.nil?

      @item = Item.find(params[:item_id])
      redirect_to(characters_url, :error => 'Unable to locate the item to destroy') if @item.nil?

      @pc.items.delete(@item)
      if @item.destroy then
        flash[:success] = "#{@item.name} deleted."
      else
        flash[:error] = "Could not delete #{@item.name}."
      end

      redirect_to :back
    rescue => exception
      flash[:error] = "Unable to remove this item due to an exception: '#{exception.message}'"
      redirect_to :back
    end
  end

  def clear_all
    begin
      @pc = current_user.characters.find(params[:id])
      redirect_to(characters_url, :error => 'You cannot clear an inventory you do not own.') if @pc.nil?

      @pc.items.delete_all
      @pc.save

      redirect_to :back
    rescue => exception
      flash[:error] = "Unable to remove this item due to an exception: '#{exception.message}'"
      redirect_to :back
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/characters/index.html.erb
<div>
  <% if current_user.characters.empty? %>
    <div class="alert alert-info text-center">
      <p>You haven't created any characters yet!</p>
      <p><%= link_to 'Create One', new_character_url, class: "btn btn-large btn-primary" %></p>
    </div>
  <% else %>
    <table class="table table-condensed">
      <tbody>
      <% current_user.characters.each do |c| %>
        <tr>
          <td><h4><%= c.name %> - <%= (c.campaign.nil?) ? 'None' : c.campaign %></h4></td>
          <td style="vertical-align: middle; text-align: right">
            <%= link_to 'View', c, class: "btn btn-small" %>
            <a href="#delCharacter" role="button" class="btn btn-small" data-toggle="modal">Delete</a>

            <div id="delCharacter" class="modal hide fade text-left">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h3>Confirm Delete</h3>
              </div>
              <div class="modal-body">
                <p>
                  <span class="label label-warning">Warning!</span> You are about to delete <%= c.name %>.
                  <span class="text-warning"><strong>This action cannot be undone</strong></span>.  If you wish to continue with this operations, please select 'OK'.
                </p>
              </div>
              <div class="modal-footer">
                <a href="#" class="btn" data-dismiss="modal">Close</a>
                <%= link_to 'OK', c, class: "btn btn-primary", method: :delete %>
              </div>
            </div>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/characters/layouts/_inventory.html.erb
<% if @pc.items.empty? %>
  <div class="text-center">
    <h4>You have no items in your inventory.</h4>
    <div class="text-center">
      <%= link_to 'Add Some Stuff!', new_character_item_url(@pc), class: 'btn btn-primary btn-large' %>
    </div>
  </div>
<% else %>
<div class="accordion" id="inv_accordion">
  <% @pc.items_by_group.each do |g, item_list| %>
      <div class="accordion-group">

        <div class="accordion-heading">
          <%= link_to "#{g}", "#collapse_#{g.parameterize.underscore}", class: 'btn btn-inverse', data: { toggle: 'collapse', parent: '#inv_accordion'} %>
        </div>

        <div id="collapse_<%= g.parameterize.underscore %>" class="accordion-body collapse">
          <% item_list.sort_by(&:name).each do |item| %>
          <div class="accordion-inner row-fluid">
            <div class="span9">
              <strong><%= item.name %></strong> (<%= item.category_name %> / <%= item.type_name %>)<br>
              <span class="muted"><%= item.description %></span>
            </div>
            <div class="span3 text-center">
              <%= link_to 'Delete', destroy_character_item_url(item.id, @pc.id), method: :post, class: 'btn btn-small btn-info' %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
  <% end %>
</div>
<% end %>

app/views/characters/layouts/_notes.html.erb
<div class="notes_display">
<%= form_for(@pc) do |f| %>
  <%= f.text_area :notes %><br />
  <%= f.submit 'Save Notes', class: 'btn btn-info' %>
<% end %>
</div>

app/views/characters/layouts/_tool_nav.html.erb
<p>
  <div class="btn-group">
    <%= link_to 'Inventory', character_inventory_url(@pc), class: "btn #{(@tool==:inventory) ? 'btn-info' : 'btn-inverse'}" %>
    <button class="btn <%= (@tool==:inventory) ? 'btn-info' : 'btn-inverse' %> dropdown-toggle tool_caret" data-toggle="dropdown">
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li><%= link_to 'Add Item...', new_character_item_url(@pc) %></li>
      <li><%= link_to 'Clear Inventory', '#modalClearInv', data: { toggle: 'modal' } %></li>
    </ul>
  </div>
</p>

<p><%= link_to 'Notes', character_notes_url(@pc), class: "btn #{(@tool==:notes) ? 'btn-info' : 'btn-inverse'}" %></p>


<div id="modalClearInv" class="modal hide fade">
  <%= form_for @pc do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Clear Inventory</h3>
      </div>

      <div class="modal-body">
        <p>
          You are about to remove all items from <%= @pc.name %>'s inventory.  <span class="label label-danger">This action cannot be undone.</span>
          Press 'Yes, clear my inventory' to proceed.
        </p>
      </div>

      <div class="modal-footer">
        <a href="#" class="btn" data-dismiss="modal">Close</a>
        <%= link_to 'Yes, clear my inventory', clear_inventory_url(@pc), method: :post, class: 'btn btn-danger' %>
      </div>
  <% end %>
</div>

app/views/characters/new.html.erb
<div>
  <%= form_for @character do |f| %>
      <div class="row-fluid" style="line-height: 25px">
        <div class="span2 text-right"><%= f.label :name, 'Character\'s name' %></div>
        <div class="span4"><%= f.text_field :name, style: 'width: 300px' %></div>
        <div class="span6"><a href="#" rel="tooltip" data-toggle="tooltip" data-placement="right" title="A name for your character"><span class="badge badge-info">?</span></a></div>
      </div>

      <div class="row-fluid" style="line-height: 25px">
        <div class="span2 text-right"><%= f.label :campaign, 'Campaign' %></div>
        <div class="span4"><%= f.text_field :campaign, style: 'width: 300px' %></div>
        <div class="span6"><a href="#" rel="tooltip" data-toggle="tooltip" data-placement="right" title="Use this field to identify the campaign/table the character belongs to"><span class="badge badge-info">?</span></a></div>
      </div>

      <div class="row-fluid" style="line-height: 25px">
        <div class="span2 text-right"><%= f.label :money, 'Starting Creds' %></div>
        <div class="span4"><%= f.text_field :money %></div>
        <div class="span6"><a href="#" rel="tooltip" data-toggle="tooltip" data-placement="right" title="The amount of credits the character has when you create it"><span class="badge badge-info">?</span></a></div>
      </div>

      <hr/>
      <div class="row-fluid" style="line-height: 25px">
        <div class="span2"></div>
        <div class="span4"><%= f.submit class: "btn btn-primary" %></div>
        <div class="span6"></div>
      </div>
  <% end %>
</div>

app/views/characters/show.html.erb
<div class="row-fluid">
  <div class="row-fluid">
    <div class="span7 character_name"><%= @pc.name %></div>
    <div class="span5 character_money">
      <a href="#modalAdjustMoney" role="button" class="btn btn-small btn-info" data-toggle="modal">Adjust</a>
      Credits: <span class="character_money value"><%= number_to_currency(@pc.money) %></span>
    </div>
  </div>

  <div class="spacer-row-15px"></div>


  <div class="row-fluid">
    <div class="span2 tool_nav">
      <%= render 'characters/layouts/tool_nav' %>
    </div>
    <div class="span10 inv_display">
      <% if @tool == :inventory %>
        <%= render 'characters/layouts/inventory' %>
      <% else %>
        <%= render 'characters/layouts/notes' %>
      <% end %>
    </div>
  </div>
</div>

<div id="modalAdjustMoney" class="modal hide fade">
  <%= form_for @pc do |f| %>
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Adjust Credits</h3>
  </div>

  <div class="modal-body">
    <p>
      Enter the amount to change your credits.  To reduce the value, enter a negative number.  To increase the value
      enter a positive number.
    </p>
    <p>
      <%= f.text_field :money, value: '' %>
    </p>
  </div>

  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">Close</a>
    <%= f.submit class: 'btn btn-primary' %>
  </div>
  <% end %>
</div>

app/views/items/new.html.erb
<div>
  <%= form_for @item, url: create_character_item_url(params[:char_id]) do |f| %>
      <%= f.error_messages %>
      <div class="row-fluid" style="line-height: 25px">
        <div class="span2 text-right"><%= f.label :name, 'Item\'s name' %></div>
        <div class="span4"><%= f.text_field :name, style: 'width: 300px' %></div>
        <div class="span6"><a href="#" rel="tooltip" data-toggle="tooltip" data-placement="right" title="This item's name."><span class="badge badge-info">?</span></a></div>
      </div>

      <div class="row-fluid" style="line-height: 25px">
        <div class="span2 text-right"><%= f.label :item_type, 'Type' %></div>
        <div class="span4"><%= f.collection_select :item_type, ItemType.all.sort_by(&:name), :id, :name, style: 'width: 300px' %></div>
        <div class="span6"><a href="#" rel="tooltip" data-toggle="tooltip" data-placement="right" title="What type of item is this?"><span class="badge badge-info">?</span></a></div>
      </div>

      <div class="row-fluid" style="line-height: 25px">
        <div class="row-fluid">
          <div class="span2 text-right"><%= f.label :description, 'Description' %></div>
          <div class="span10"><a href="#" rel="tooltip" data-toggle="tooltip" data-placement="right" title="A description of this item (stats, special abilities, etc)"><span class="badge badge-info">?</span></a></div>
        </div>
        <div class="row-fluid">
          <div class="span2"></div>
          <div class="span10"><%= f.text_area :description, style: 'width: 300px' %></div>
        </div>
      </div>

      <hr/>
      <div class="row-fluid" style="line-height: 25px">
        <div class="span2"></div>
        <div class="span8">
          <%= f.submit 'Add to inventory', class: "btn btn-primary" %>
          <%= link_to 'Cancel', :back, class: 'btn' %>
        </div>
        <div class="span2"></div>
      </div>
  <% end %>
</div>

app/views/layouts/_login.html.erb
<div class="hero-unit">
  <p>
    Track your characters, keep your notes, join your friends!  Log in to get started.
  </p>
  <p>
    <a class="btn btn-primary btn-large" href="<%= new_user_session_path %>">Log In!</a>
  </p>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class='navbar-inner'>
    <div class="container-fluid">
      <%= link_to 'Eclipse Phase', root_url, class: 'brand' %>
      <div>

        <ul class="nav">
          <li class="divider-vertical"></li>
          <li class=""><a href="<%= root_url %>">Home</a></li>

          <li class="divider-vertical"></li>
          <% if user_signed_in? then %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Characters <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Create New...', new_character_url %></li>
                  <li><%= link_to 'View My Characters', characters_url %></li>
                </ul>
              </li>
              <li class="divider-vertical"></li>

              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'My Profile', edit_user_registration_url %></li>
                </ul>
              </li>

              <li class="pull-right"><%= link_to 'Logout', destroy_user_session_url, method: :delete %></li>
          <% else %>
              <li><%= link_to 'Login', new_user_session_url %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eclipse Phase Player Assistant</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>
<div class="jumbotron"></div>
<div class="spacer-row-15px"></div>
<div class="container">
  <div class="row-fluid">
    <% flash.each do |key, msg| %>
        <div id="<%= key %>" class="alert alert-<%= key %>">
          <p><%= msg %></p>
        </div>
    <% end %>
  </div>
  <div class="row-fluid">
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/static_pages/index.html.erb
<% if user_signed_in? %>
    Hello <%= current_user.display_name %>!
<% else %>
    <%= render "layouts/login" %>
<% end %>